### ISSUE TITLE
Unhandled Exceptions on launching the app for first time

### ISSUE THREAD

**Issue by DreamyPhobic** [odk-x/skunkworks-parrot#61]
### Steps to reproduce
For new users, start from step - 3, other users can start from step-1
1. Delete keys.json file.
2. Close the app.
3. Re-Launch the app and click on 'Configure'.
4. You will get 'NoSuchFileException'.
### Expected Behaviour
It should first look up for the file before accessing it.

**Comment by Shubhamr837** [comment]
@opendatakit-bot claim

**Comment by Shubhamr837** [comment]
@opendatakit-bot claim --force
