### ISSUE TITLE
Show proper error messages during login.

### ISSUE THREAD

**Issue by DreamyPhobic** [odk-x/skunkworks-parrot#62]
### Steps to reproduce
1. Go on to your Sync Endpoint server https://[Your_hosted_url]:40000
2. Create a user with Default group other than 'site admins' . For info see [this](https://docs.opendatakit.org/odk-x/sync-endpoint/#creating-users)
3. Try to login into the app with the aforementioned new user.
4. App will show this message "Invalid username/password, please try again."
### Expected Behaviour
App should show proper error message with possible solution.

**Comment by codeknight3** [comment]
@opendatakit-bot claim

**Comment by codeknight3** [comment]
@opendatakit-bot claim --force
